# -*- coding: utf-8 -*-
"""Gerak Jatuh Bebas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BBsZVQktdpFkpS_FiDgSMU8oABM-A9nI
"""

# Muhammad Hafidh Raditya
# 1301184079
import matplotlib.pyplot as plt
import math
from matplotlib import style
style.use('fivethirtyeight')

# Insialisasi variabel awal pada bola
y0 = 100.0     #ketinggian awal
v0 = 0.0      #kecepatan awal
t0= 0.0       #waktu awal
g = -9.8      #percepatan gravitasi
dt = 0.001      #selisih waktu

# Buat array untuk menampung variabel tinggi, kecepatan, dan waktu pada setiap dt
y = []
v = []
t = []

# Inisialisasi ketinggian awal, kecepatan awal, dan waktu awal
ketinggian = y0
kecepatan = v0
waktu = t0

y.append(ketinggian)
v.append(kecepatan)
t.append(waktu)

# Proses iterasi numerikal
while ketinggian>0:
  waktu = waktu+dt
  t.append(waktu)
  kecepatan = kecepatan+(g*dt)
  v.append(1*kecepatan)
  ketinggian = ketinggian+(kecepatan*dt)
  y.append(ketinggian)
  # print("waktu = ",waktu)
  # print("kecepatan = ",kecepatan)
  # print("ketinggian = ",ketinggian)

# proses iterasi analitikal
yAnalytical = []
for i in t:
  yA = y[0]+(0.5*g*i**2)
  yAnalytical.append(yA)
tAnalytical = math.sqrt((2*-y0)/g)

# numerical graph
plt.plot(t, y, c='b', label='numerical')
# analytical graph
plt.plot(t, yAnalytical, c='r', label='analytical')
# plot properties
plt.xlabel('waktu')
plt.ylabel('ketinggian')
plt.xlim(-0.5,5)
plt.ylim(-5,105)
plt.legend()
plt.show()


print("waktu numerikal = ",t[len(t)-1])
print("waktu analitikal = ",tAnalytical)